import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";
import Provider from "@/components/provider";
const inter = Arimo({ subsets: ["latin"], weight: ['400']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-auto min-h-[100vh] flex flex-col`}>
        <Provider>
          <Header/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
