import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import Provider from "@/components/provider";
import "../globals.css";

const inter = Arimo({ subsets: ["latin"], weight: ['400']});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${inter.className} overflow-auto min-h-[100vh] flex flex-col`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
